{% set name = "Phosphoros" %}
{% set version = "0.18" %}
{% set build_number = environ.get('GIT_DESCRIBE_NUMBER', '0') %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    git_rev: feature/ScaleFactorSampling
    git_url: https://{{ environ.get('GIT_USER', '') }}@gitlab.euclid-sgs.uk/SDC-CH/Phosphoros.git
    patches:
      - trigger_compiler_id.patch

build:
    number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

test:
    commands:
        - $PREFIX/bin/Phosphoros --version

requirements:
    build:
        - cmake >=3.0
        - make
        - {{ compiler('cxx') }}
        - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
        - {{ cdt('libx11-devel') }}          # [linux]
        - {{ cdt('libxext-devel') }}         # [linux]
        - {{ cdt('libxrender-devel') }}      # [linux]
        - {{ cdt('libxau-devel') }}          # [linux]
        - {{ cdt('mesa-libgl-devel') }}      # [linux]
        - {{ cdt('mesa-libegl-devel') }}     # [linux]
        - {{ cdt('mesa-dri-drivers') }}      # [linux]
        - {{ cdt('libxdamage') }}            # [linux]
        - {{ cdt('libxdamage-devel') }}      # [linux]
        - {{ cdt('libxxf86vm') }}            # [linux]
        - {{ cdt('libxfixes') }}             # [linux]
        - {{ cdt('libxfixes-devel') }}       # [linux]
        - {{ cdt('libselinux-devel') }}      # [linux]
    host:
        - python
        - boost-cpp
        - phosphoroscore ==1.0
        - qt >=5.9,<6
        - cfitsio >=3.470
        - CCfits >=2.5
        - lxml >=4.5
    run:
        - {{ pin_compatible('python', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_compatible('boost-cpp', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_compatible('CCfits') }}
        - astropy
        - matplotlib
        - scipy

test:
    commands:
        - $PREFIX/bin/Phosphoros --version

app:
    entry: Phosphoros GUI
    icon: phosphoros_64.png
    summary: A photometric redshift determination tool based on a template fitting method.
    description: A photometric redshift determination tool based on a template fitting method.
    own_environment: True

about:
    home: http://isdc.unige.ch/euclid/phosphoros/
    license: LGPL
    summary: A photometric redshift determination tool based on a template fitting method.

